name: monyx
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  fl_chart: ^0.63.0
  flutter_screenutil: ^5.9.3
  table_calendar: ^3.0.9
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  get: ^4.7.2
  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  permission_handler: ^11.3.1
  android_intent_plus: ^4.0.3
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/static/Inter_28pt-Regular.ttf
        - asset: fonts/Inter/static/Inter_28pt-Bold.ttf
          weight: 700
